Introduccion pandas

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(data=[(0,1,2),(1,2,3),(2,3,5),(3,4,5)])

   0  1  2
0  0  1  2
1  1  2  3
2  2  3  5
3  3  4  5

In [ ]:
diccionarios={"Curso1":[10,5,33,45,25,22],"Curso2":[0,15,21,30,31,11],"Curso3":[15,5,1,10,42,21],"Curso4":[20,35,3,15,0,0]}

In [ ]:
datos=pd.DataFrame(data=diccionarios)
datos

   Curso1  Curso2  Curso3  Curso4
0      10       0      15      20
1       5      15       5      35
2      33      21       1       3
3      45      30      10      15
4      25      31      42       0
5      22      11      21       0

In [ ]:
import numpy as np

In [ ]:
matrix= np.arange(9).reshape(3,3)

In [ ]:
pd.DataFrame (matrix)

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [ ]:
indice=("enero","febrero","marzo","abril","mayo","junio")

In [ ]:
puntuacion=pd.DataFrame(data=diccionarios, index=indice)
puntuacion

         Curso1  Curso2  Curso3  Curso4
enero        10       0      15      20
febrero       5      15       5      35
marzo        33      21       1       3
abril        45      30      10      15
mayo         25      31      42       0
junio        22      11      21       0

In [ ]:
pd.DataFrame(matrix,index=["uno","dos","tres"],columns=["a","b","c"])

      a  b  c
uno   0  1  2
dos   3  4  5
tres  6  7  8

In [ ]:
puntuacion["Curso3"]

enero      15
febrero     5
marzo       1
abril      10
mayo       42
junio      21
Name: Curso3, dtype: int64

In [ ]:
datos_np=np.arange(1,13).reshape(3, 4)

In [ ]:
num=pd.DataFrame(datos_np)
num

   0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [ ]:
num[2]

0     3
1     7
2    11
Name: 2, dtype: int64

In [ ]:
datos[3]#Cuando las columnas tienen un indice se dbe llamar por el nombre

KeyError: 3

In [ ]:
puntuacion[:1]#De este modo se toman los datos a partir de las filas (inicio:final-1)

       Curso1  Curso2  Curso3  Curso4
enero      10       0      15      20

In [ ]:
puntuacion[::2]#De esta forma se toman los datos cada dos pasos

       Curso1  Curso2  Curso3  Curso4
enero      10       0      15      20
marzo      33      21       1       3
mayo       25      31      42       0

In [ ]:
puntuacion["enero":"mayo"]

         Curso1  Curso2  Curso3  Curso4
enero        10       0      15      20
febrero       5      15       5      35
marzo        33      21       1       3
abril        45      30      10      15
mayo         25      31      42       0

In [ ]:
puntuacion["Curso2"][2]

/tmp/ipykernel_20732/620723389.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  puntuacion["Curso2"][2]

np.int64(21)

In [ ]:
puntuacion["Curso1"][0:5]

enero      10
febrero     5
marzo      33
abril      45
mayo       25
Name: Curso1, dtype: int64

Cada DataFrame se compone de varias series, las series son los vectores que pertenecen a esas matrices (DataFrames)

In [ ]:
pd.Series([12,1,5,4,8],name="py201")

0    12
1     1
2     5
3     4
4     8
Name: py201, dtype: int64

In [ ]:
indice1=["enero","febrero","marzo","abril","mayo"]

In [ ]:
Serie=pd.Series([12,1,5,4,8],name="py201",index=indice1)
Serie

enero      12
febrero     1
marzo       5
abril       4
mayo        8
Name: py201, dtype: int64

Operaciones basicas con pandas

In [ ]:


from datetime import datetime

In [ ]:
indice = ['gerente', 'supervisor', 'vendedor', 'cajero']
personal = pd.DataFrame({'nombres':('Juan Pérez',
                                    'María Sánchez',
                                    'Jorge Vargas',
                                    'Rodrigo Martínez'),'fechas':(datetime(1995,12,21),
                      datetime(1989,1,13),
                      datetime(1992,9,14),
                      datetime(1993,7,8)),
            'saldo': (2500,
                      5345,
                      np.nan,
                      11323.2),
            'al corriente':(True,
                            True,
                            False,
                            True)}, index=indice)
personal

                     nombres     fechas    saldo  al corriente
gerente           Juan Pérez 1995-12-21   2500.0          True
supervisor     María Sánchez 1989-01-13   5345.0          True
vendedor        Jorge Vargas 1992-09-14      NaN         False
cajero      Rodrigo Martínez 1993-07-08  11323.2          True

In [ ]:
personal.shape

(4, 4)

In [ ]:
personal.index#Para saber los valores de los indices

Index(['gerente', 'supervisor', 'vendedor', 'cajero'], dtype='object')

In [ ]:
personal.columns#Para saber los nombres de las columnas

Index(['nombres', 'fechas', 'saldo', 'al corriente'], dtype='object')

In [ ]:
personal.reset_index()

        index           nombres     fechas    saldo  al corriente
0     gerente        Juan Pérez 1995-12-21   2500.0          True
1  supervisor     María Sánchez 1989-01-13   5345.0          True
2    vendedor      Jorge Vargas 1992-09-14      NaN         False
3      cajero  Rodrigo Martínez 1993-07-08  11323.2          True

In [ ]:
p=personal.set_index("nombres")#Para cambiar el indice por una de los columnas en este caso nombres
p

                     fechas    saldo  al corriente
nombres
Juan Pérez       1995-12-21   2500.0          True
María Sánchez    1989-01-13   5345.0          True
Jorge Vargas     1992-09-14      NaN         False
Rodrigo Martínez 1993-07-08  11323.2          True

In [ ]:
personal.info()#Para saber los tipos de dtaos que hay en cada columnas

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, gerente to cajero
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nombres       4 non-null      object
 1   fechas        4 non-null      datetime64[ns]
 2   saldo         3 non-null      float64
 3   al corriente  4 non-null      bool
dtypes: bool(1), datetime64[ns](1), float64(1), object(1)
memory usage: 304.0+ bytes

In [ ]:
datos=pd.DataFrame(np.arange(20).reshape(5,4),columns=("primero","segundo","tercero","cuarto"))
datos

   primero  segundo  tercero  cuarto
0        0        1        2       3
1        4        5        6       7
2        8        9       10      11
3       12       13       14      15
4       16       17       18      19

In [ ]:
datos.iloc[2,[3]]#Para obtener la serie

cuarto    11
Name: 2, dtype: int64

In [ ]:
datos.iloc[2,3]#Para obtener el valor numerico

np.int64(11)

In [ ]:
datos.iloc[2,[2,1 ,3, 2]]#Para seleccionar series especificas

tercero    10
segundo     9
cuarto     11
tercero    10
Name: 2, dtype: int64

In [ ]:
personal.loc["supervisor",["fechas"]]

fechas    1989-01-13 00:00:00
Name: supervisor, dtype: object

In [ ]:
personal["saldo"]>3000

gerente       False
supervisor     True
vendedor      False
cajero         True
Name: saldo, dtype: bool

In [ ]:
personal.loc[personal["saldo"]>3000]#forma de sacar los que cumplan la condicion dada

                     nombres     fechas    saldo  al corriente
supervisor     María Sánchez 1989-01-13   5345.0          True
cajero      Rodrigo Martínez 1993-07-08  11323.2          True

In [ ]:
personal.loc[personal["al corriente"]]

                     nombres     fechas    saldo  al corriente
gerente           Juan Pérez 1995-12-21   2500.0          True
supervisor     María Sánchez 1989-01-13   5345.0          True
cajero      Rodrigo Martínez 1993-07-08  11323.2          True

In [ ]:
personal.loc[personal["al corriente"]==False]

               nombres     fechas  saldo  al corriente
vendedor  Jorge Vargas 1992-09-14    NaN         False

In [ ]:
indice_1 = ("lunes", "martes", "miércoles")
marco_1 = pd.DataFrame({'Centro':[1520,1640,1043],
                       'Sur':[1422,1673,1534],
                      'Oriente':[1021,1073,1100]},
                       index=indice_1)

indice_2 = ("jueves", "viernes", "sábado")
marco_2 = pd.DataFrame({'Centro':[1321,1459,1875],
                       'Sur':[1622,1841,1920],
                      'Oriente':[1500,1432,1491]},
                      index=indice_2)

In [ ]:
marco_2

         Centro   Sur  Oriente
jueves     1321  1622     1500
viernes    1459  1841     1432
sábado     1875  1920     1491

In [ ]:
marco_1

           Centro   Sur  Oriente
lunes        1520  1422     1021
martes       1640  1673     1073
miércoles    1043  1534     1100

In [ ]:
pd.concat([marco_1,marco_2],axis=0)

lunes        1520
martes       1640
miércoles    1043
jueves       1321
viernes      1459
sábado       1875
Name: Centro, dtype: int64

In [ ]:
pd.concat([marco_1,marco_2],axis=1)

           Centro     Sur  Oriente  Centro     Sur  Oriente
lunes      1520.0  1422.0   1021.0     NaN     NaN      NaN
martes     1640.0  1673.0   1073.0     NaN     NaN      NaN
miércoles  1043.0  1534.0   1100.0     NaN     NaN      NaN
jueves        NaN     NaN      NaN  1321.0  1622.0   1500.0
viernes       NaN     NaN      NaN  1459.0  1841.0   1432.0
sábado        NaN     NaN      NaN  1875.0  1920.0   1491.0

In [ ]:
pd.concat([marco_1,marco_2],axis=0)["Centro"]

lunes        1520
martes       1640
miércoles    1043
jueves       1321
viernes      1459
sábado       1875
Name: Centro, dtype: int64